name: Run tests and build

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "v1.5.4"

      - name: Run tests
        run: deno test --allow-env --allow-read --allow-net --unstable;
